/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miespotify.Vistas;



import java.awt.Image;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Controladores.CUsuario;
import static Controladores.CUsuario.persistirUsuario;
import Entidades.Usuario;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Persistence;



/**
 *
 * @author Mauricio
 */
public class AltaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form AltaUsuario
     */
    public AltaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        lbNickname = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbFechaNacimiento = new javax.swing.JLabel();
        botonAceptarAltaPerfil = new javax.swing.JButton();
        botonCancelarAltaPerfil = new javax.swing.JButton();
        txtNickname = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtFechaNacimiento = new com.toedter.calendar.JDateChooser();
        botonExaminarFotoPerfil = new javax.swing.JButton();
        lbFotoPerfil = new javax.swing.JLabel();
        botonLimpiarAltaPerfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(625, 500));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("ALTA USUARIO");

        lbNickname.setText("Nickname:");

        lbEmail.setText("E-Mail:");

        lbNombre.setText("Nombre:");

        lbApellido.setText("Apellido:");

        lbFechaNacimiento.setText("Fecha nacimiento:");

        botonAceptarAltaPerfil.setText("Aceptar");
        botonAceptarAltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarAltaPerfilActionPerformed(evt);
            }
        });

        botonCancelarAltaPerfil.setText("Cancelar");
        botonCancelarAltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAltaPerfilActionPerformed(evt);
            }
        });

        txtNickname.setAutoscrolls(false);
        txtNickname.setName("txtNickname"); // NOI18N
        txtNickname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicknameActionPerformed(evt);
            }
        });

        botonExaminarFotoPerfil.setText("Examinar");
        botonExaminarFotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonExaminarFotoPerfilActionPerformed(evt);
            }
        });

        lbFotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFotoPerfil.setText("FOTO");
        lbFotoPerfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botonLimpiarAltaPerfil.setText("Limpiar");
        botonLimpiarAltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarAltaPerfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbApellido)
                            .addComponent(lbNombre)
                            .addComponent(lbEmail)
                            .addComponent(lbNickname)
                            .addComponent(lbFechaNacimiento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(64, 64, 64)
                                    .addComponent(jLabel1)
                                    .addGap(77, 77, 77))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptarAltaPerfil)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonLimpiarAltaPerfil)
                        .addGap(18, 18, 18)
                        .addComponent(botonCancelarAltaPerfil))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbFotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonExaminarFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNickname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNickname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbFechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCancelarAltaPerfil)
                            .addComponent(botonAceptarAltaPerfil)
                            .addComponent(botonLimpiarAltaPerfil))
                        .addGap(105, 105, 105))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbFotoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonExaminarFotoPerfil)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        txtNickname.getAccessibleContext().setAccessibleName("nickname");
        txtNickname.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Patron para validar Email
    Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        
    
    
    
    
    private void botonAceptarAltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarAltaPerfilActionPerformed
        
        
        
        if(txtNickname.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un nickname");
            return;
        }
        
        if(txtEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un email");
            return;
        }
        
        Matcher mather = pattern.matcher(txtEmail.getText());
 
        if (mather.find() != true) {
            JOptionPane.showMessageDialog(null,"El email ingresado es inválido.");
            return;
        }         
                
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un nombre");
            return;
        }
        
        if(txtApellido.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Debe ingresar un apellido");
            return;
        }
        
        if(txtFechaNacimiento.getDate() == null){
            JOptionPane.showMessageDialog(null,"Debe ingresar una fecha");
        }
        
        Usuario u;
        
        /*Convertimos la fecha tipo Date a String*/
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyy");
        
        Date fecha = txtFechaNacimiento.getDate();
        
        String FechaCadena = sdf.format(fecha);
        
        //Luego pasamos como parametro al crear el usario.
        
        u = new Usuario(txtNickname.getText(),txtEmail.getText(),txtNombre.getText(),txtApellido.getText(),FechaCadena,"FotoPerfil");
               
        
            try{
                
                persistirUsuario(u);
                    
                JOptionPane.showMessageDialog(null,"Usuario dado de alta");
                
                this.dispose();
                
            
            }catch(Exception ex){
                  
                JOptionPane.showMessageDialog(null,"ERROR: no se pudo dar de alta el usuario\n" + ex);
                
            }
        
        
        
    //termina boton aceptar   
    }//GEN-LAST:event_botonAceptarAltaPerfilActionPerformed

    private void botonCancelarAltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAltaPerfilActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_botonCancelarAltaPerfilActionPerformed

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed
       
    File FotoPerfil;
    
    private void botonExaminarFotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonExaminarFotoPerfilActionPerformed
            
        int resultado;
        
        CargarFoto ventana = new CargarFoto();
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG, PNG, BMP o GIF","jpg","png","bmp","gif");
        
        ventana.jfchCargarFoto.setFileFilter(filter);
        
        resultado = ventana.jfchCargarFoto.showOpenDialog(null);
        
        if(JFileChooser.APPROVE_OPTION == resultado){
            
            FotoPerfil = ventana.jfchCargarFoto.getSelectedFile();
            
            try{
                
                ImageIcon icon = new ImageIcon(FotoPerfil.toString());
                
                Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lbFotoPerfil.getWidth(),lbFotoPerfil.getHeight(),Image.SCALE_DEFAULT));
                        
                lbFotoPerfil.setText(null);        
                        
                lbFotoPerfil.setIcon(icono);
                
            }catch(Exception ex){
                
                JOptionPane.showMessageDialog(rootPane, ex );
                
            }
            
        }
        
    }//GEN-LAST:event_botonExaminarFotoPerfilActionPerformed

    private void botonLimpiarAltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarAltaPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLimpiarAltaPerfilActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptarAltaPerfil;
    private javax.swing.JButton botonCancelarAltaPerfil;
    private javax.swing.JButton botonExaminarFotoPerfil;
    private javax.swing.JButton botonLimpiarAltaPerfil;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFechaNacimiento;
    private javax.swing.JLabel lbFotoPerfil;
    private javax.swing.JLabel lbNickname;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private com.toedter.calendar.JDateChooser txtFechaNacimiento;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void FileNameExtensionFilter() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
